# Generated by Django 3.2 on 2023-01-27 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='minute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)]),
        ),
    ]
