# Generated by Django 3.2 on 2023-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230127_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('p', 'PRICE'), ('v', 'VOLUME')], default='p', max_length=1),
        ),
    ]
