coins_symbols_colors = {'Amp': {'symbol': 'AMP', 'color': '#af4618'},
                        'USD Coin': {'symbol': 'USDC', 'color': '#20bbfe'},
                        'Bitcoin Standard Hashrate Token': {'symbol': 'BTCST', 'color': '#53dbe8'},
                        'Phala Network': {'symbol': 'PHA', 'color': '#1da63b'},
                        'Ultra Salescloud': {'symbol': 'UST', 'color': '#2a2218'},
                        'Reef': {'symbol': 'REEF', 'color': '#5112ce'}, 'Siacoin': {'symbol': 'SC', 'color': '#169f2c'},
                        'Frax Share': {'symbol': 'FXS', 'color': '#6ef89f'},
                        'Harmony': {'symbol': 'ONE', 'color': '#5f4b21'},
                        'Livepeer': {'symbol': 'LPT', 'color': '#af800c'},
                        'Avalanche': {'symbol': 'AVAX', 'color': '#163e76'},
                        'RSK Infrastructure Framework': {'symbol': 'RIF', 'color': '#956c97'},
                        'Litecoin': {'symbol': 'LTC', 'color': '#73b0cc'},
                        'Verge': {'symbol': 'XVG', 'color': '#d35ae7'},
                        'Hedera': {'symbol': 'HBAR', 'color': '#62526d'},
                        'Kyber Network Crystal v2': {'symbol': 'KNC', 'color': '#911d27'},
                        'Dash': {'symbol': 'DASH', 'color': '#b7ee8f'},
                        'Bitcoin Gold': {'symbol': 'BTG', 'color': '#402604'},
                        'Komodo': {'symbol': 'KMD', 'color': '#42c4a6'},
                        'Ethereum Classic': {'symbol': 'ETC', 'color': '#fbd294'},
                        'Flamingo': {'symbol': 'FLM', 'color': '#ffe0bf'},
                        'Illuvium': {'symbol': 'ILV', 'color': '#8762dd'},
                        'Ontology': {'symbol': 'ONT', 'color': '#6f481'},
                        'Flow': {'symbol': 'FLOW', 'color': '#5e8c12'},
                        'Filecoin': {'symbol': 'FIL', 'color': '#a4d2bc'},
                        'Powerledger': {'symbol': 'POWR', 'color': '#189e02'},
                        'Ankr': {'symbol': 'ANKR', 'color': '#ad7221'}, 'IoTeX': {'symbol': 'IOTX', 'color': '#77d28d'},
                        'Paris Saint-Germain Fan Token': {'symbol': 'PSG', 'color': '#8a89e3'},
                        'Mask Network': {'symbol': 'MASK', 'color': '#2807cc'},
                        'Nano': {'symbol': 'XNO', 'color': '#648f1c'},
                        '0x': {'symbol': 'ZRX', 'color': '#73f613'}, 'JUST': {'symbol': 'JST', 'color': '#fcc4c6'},
                        'Orchid': {'symbol': 'OXT', 'color': '#387d02'}, 'Venus': {'symbol': 'XVS', 'color': '#19f68e'},
                        'SushiSwap': {'symbol': 'SUSHI', 'color': '#963d6b'},
                        'QuickSwap': {'symbol': 'QUICK', 'color': '#e92f1'},
                        'Decred': {'symbol': 'DCR', 'color': '#497551'},
                        'PAX Gold': {'symbol': 'PAXG', 'color': '#97a598'},
                        'Kava': {'symbol': 'KAVA', 'color': '#fd9617'}, 'Holo': {'symbol': 'HOT', 'color': '#902543'},
                        'DigiByte': {'symbol': 'DGB', 'color': '#89928b'},
                        'Polkastarter': {'symbol': 'POLS', 'color': '#2bb2bc'},
                        'Polygon': {'symbol': 'MATIC', 'color': '#58188f'},
                        'Orion Protocol': {'symbol': 'ORN', 'color': '#ba9790'},
                        'Arweave': {'symbol': 'AR', 'color': '#c35812'},
                        'Badger DAO': {'symbol': 'BADGER', 'color': '#a3f328'},
                        'SafePal': {'symbol': 'SFP', 'color': '#eb34a8'}, 'BNB': {'symbol': 'BNB', 'color': '#7e889e'},
                        'Zcash': {'symbol': 'ZEC', 'color': '#bb44a8'}, 'Lisk': {'symbol': 'LSK', 'color': '#ffa425'},
                        'Metal': {'symbol': 'MTL', 'color': '#9ecb5e'},
                        'BitShares': {'symbol': 'BTS', 'color': '#207722'},
                        'TomoChain': {'symbol': 'TOMO', 'color': '#868b98'},
                        'Gitcoin': {'symbol': 'GTC', 'color': '#e147a4'},
                        'Zilliqa': {'symbol': 'ZIL', 'color': '#9fc704'},
                        'Alien Worlds': {'symbol': 'TLM', 'color': '#72e985'},
                        'aelf': {'symbol': 'ELF', 'color': '#f37ab9'},
                        'Theta Fuel': {'symbol': 'TFUEL', 'color': '#6bcb6b'},
                        'Helium': {'symbol': 'HNT', 'color': '#96c369'},
                        'Akropolis': {'symbol': 'AKRO', 'color': '#f135b4'},
                        'Wrapped NXM': {'symbol': 'WNXM', 'color': '#482cdb'},
                        'Band Protocol': {'symbol': 'BAND', 'color': '#79f56b'},
                        'Monero': {'symbol': 'XMR', 'color': '#8f6741'},
                        'Linear Finance': {'symbol': 'LINA', 'color': '#77cb5c'},
                        'Numeraire': {'symbol': 'NMR', 'color': '#6ed321'},
                        'RAMP': {'symbol': 'RAMP', 'color': '#cfc67b'},
                        'Compound': {'symbol': 'COMP', 'color': '#536751'},
                        'Ethereum': {'symbol': 'ETH', 'color': '#296c20'},
                        'Curve DAO Token': {'symbol': 'CRV', 'color': '#562fe2'},
                        'Ellipsis': {'symbol': 'EPS', 'color': '#7db96a'},
                        'Tribe': {'symbol': 'TRIBE', 'color': '#7782bb'},
                        'Bancor': {'symbol': 'BNT', 'color': '#f2da89'},
                        'StormX': {'symbol': 'STMX', 'color': '#517d2d'},
                        'Balancer': {'symbol': 'BAL', 'color': '#854c29'},
                        'The Sandbox': {'symbol': 'SAND', 'color': '#e86dee'},
                        'Polymath': {'symbol': 'POLY', 'color': '#a44bdf'},
                        'Aragon': {'symbol': 'ANT', 'color': '#58e2f6'},
                        'Chromia': {'symbol': 'CHR', 'color': '#ba7b7e'},
                        'Basic Attention Token': {'symbol': 'BAT', 'color': '#ce8122'},
                        'Dogecoin': {'symbol': 'DOGE', 'color': '#e3ffb4'},
                        'SuperFarm': {'symbol': 'SUPER', 'color': '#26cbab'},
                        'Aave': {'symbol': 'AAVE', 'color': '#546dee'},
                        'Ethernity': {'symbol': 'ERN', 'color': '#e0bcd7'},
                        'COTI': {'symbol': 'COTI', 'color': '#90a475'},
                        'Beam': {'symbol': 'BEAM', 'color': '#5777c6'}, 'XRP': {'symbol': 'XRP', 'color': '#a57a8d'},
                        'Horizen': {'symbol': 'ZEN', 'color': '#f508f9'},
                        'Alpha Venture DAO': {'symbol': 'ALPHA', 'color': '#1f7da4'},
                        'UMA': {'symbol': 'UMA', 'color': '#f691f4'}, 'Klaytn': {'symbol': 'KLAY', 'color': '#4c177f'},
                        'Cardano': {'symbol': 'ADA', 'color': '#6f084c'},
                        'Kusama': {'symbol': 'KSM', 'color': '#393628'},
                        'Ravencoin': {'symbol': 'RVN', 'color': '#2f2db8'},
                        'Dent': {'symbol': 'DENT', 'color': '#dd407f'},
                        'Uniswap': {'symbol': 'UNI', 'color': '#bcb253'},
                        'Ampleforth Governance Token': {'symbol': 'FORTH', 'color': '#cce399'},
                        'Cartesi': {'symbol': 'CTSI', 'color': '#59994a'},
                        'Elrond': {'symbol': 'EGLD', 'color': '#a2ec45'},
                        'Ocean Protocol': {'symbol': 'OCEAN', 'color': '#facfec'},
                        'Bonfida': {'symbol': 'FIDA', 'color': '#f57e9e'},
                        'Audius': {'symbol': 'AUDIO', 'color': '#6513e3'},
                        'TRON': {'symbol': 'TRX', 'color': '#c03a8e'},
                        'Mina': {'symbol': 'MINA', 'color': '#d394f9'},
                        'SKALE Network': {'symbol': 'SKL', 'color': '#a7bf6f'},
                        'Firo': {'symbol': 'FIRO', 'color': '#d9346c'},
                        'Trust Wallet Token': {'symbol': 'TWT', 'color': '#251c9a'},
                        'Nervos Network': {'symbol': 'CKB', 'color': '#778454'},
                        'IOTA': {'symbol': 'MIOTA', 'color': '#5436f3'},
                        'WAX': {'symbol': 'WAXP', 'color': '#f13d8f'}, 'Maker': {'symbol': 'MKR', 'color': '#76d8ca'},
                        'OMG Network': {'symbol': 'OMG', 'color': '#c1eb64'},
                        'Chiliz': {'symbol': 'CHZ', 'color': '#f5ed78'},
                        'Harvest Finance': {'symbol': 'FARM', 'color': '#359ed3'},
                        'MyNeighborAlice': {'symbol': 'ALICE', 'color': '#78b73b'},
                        'WOO Network': {'symbol': 'WOO', 'color': '#cb601d'},
                        'eCash': {'symbol': 'XEC', 'color': '#55164e'},
                        'PlayDapp': {'symbol': 'PLA', 'color': '#29a231'},
                        'WINkLink': {'symbol': 'WIN', 'color': '#3cde89'},
                        'Ardor': {'symbol': 'ARDR', 'color': '#3db827'},
                        'Stellar': {'symbol': 'XLM', 'color': '#9fbfbe'},
                        '1inch Network': {'symbol': '1INCH', 'color': '#c1471d'},
                        'Automata Network': {'symbol': 'ATA', 'color': '#eda851'},
                        'Celo': {'symbol': 'CELO', 'color': '#818787'},
                        'Wanchain': {'symbol': 'WAN', 'color': '#8e602'},
                        'THORChain': {'symbol': 'RUNE', 'color': '#54c3af'},
                        'MOBOX': {'symbol': 'MBOX', 'color': '#962cd9'},
                        'Augur': {'symbol': 'REP', 'color': '#2379a4'},
                        'Enjin Coin': {'symbol': 'ENJ', 'color': '#77b749'},
                        'Polkadot': {'symbol': 'DOT', 'color': '#d2bcc1'},
                        'Oasis Network': {'symbol': 'ROSE', 'color': '#b78f8e'},
                        'Toko Token': {'symbol': 'TKO', 'color': '#97c308'},
                        'Tether': {'symbol': 'USDT', 'color': '#f74fe9'},
                        'Steem': {'symbol': 'STEEM', 'color': '#f11a4c'},
                        'IRISnet': {'symbol': 'IRIS', 'color': '#2d94ce'},
                        'Aavegotchi': {'symbol': 'GHST', 'color': '#733fc7'},
                        'Theta Network': {'symbol': 'THETA', 'color': '#5c18a0'},
                        'Raydium': {'symbol': 'RAY', 'color': '#670b4f'},
                        'Request': {'symbol': 'REQ', 'color': '#bf9c1e'},
                        'Chainlink': {'symbol': 'LINK', 'color': '#f1808e'},
                        'TrueUSD': {'symbol': 'TUSD', 'color': '#7244f9'},
                        'Gnosis': {'symbol': 'GNO', 'color': '#ec6d97'}, 'CLV': {'symbol': 'CLV', 'color': '#697260'},
                        'Virtua': {'symbol': 'TVK', 'color': '#3b5d92'},
                        'Enzyme': {'symbol': 'MLN', 'color': '#9a86c9'},
                        'Coin98': {'symbol': 'C98', 'color': '#7f9c34'},
                        'Synthetix': {'symbol': 'SNX', 'color': '#ef1792'},
                        'Mirror Protocol': {'symbol': 'MIR', 'color': '#bd0da9'},
                        'VeChain': {'symbol': 'VET', 'color': '#e8fc45'},
                        'Waves': {'symbol': 'WAVES', 'color': '#618886'}, 'SXP': {'symbol': 'SXP', 'color': '#752982'},
                        'Loopring': {'symbol': 'LRC', 'color': '#1b7df7'},
                        'Quant': {'symbol': 'QNT', 'color': '#32caa7'},
                        'IOST': {'symbol': 'IOST', 'color': '#d503e2'},
                        'Alpaca Finance': {'symbol': 'ALPACA', 'color': '#771428'},
                        'Litentry': {'symbol': 'LIT', 'color': '#93f6cc'},
                        'Reserve Rights': {'symbol': 'RSR', 'color': '#cb2f83'},
                        'Ren': {'symbol': 'REN', 'color': '#5454ad'},
                        'Origin Protocol': {'symbol': 'OGN', 'color': '#5c2d6c'},
                        'Shiba Inu': {'symbol': 'SHIB', 'color': '#8b637b'},
                        'PancakeSwap': {'symbol': 'CAKE', 'color': '#532710'},
                        'WazirX': {'symbol': 'WRX', 'color': '#5831f1'},
                        'Pundi X (New)': {'symbol': 'PUNDIX', 'color': '#ed396a'},
                        'Syscoin': {'symbol': 'SYS', 'color': '#f85bba'},
                        'Alchemy Pay': {'symbol': 'ACH', 'color': '#8221df'},
                        'Render Token': {'symbol': 'RNDR', 'color': '#2fdbe1'},
                        'Decentraland': {'symbol': 'MANA', 'color': '#f39a3c'},
                        'Secret': {'symbol': 'SCRT', 'color': '#1b8551'},
                        'Storj': {'symbol': 'STORJ', 'color': '#a41145'},
                        'Nexo': {'symbol': 'NEXO', 'color': '#4c73c6'},
                        'Bitcoin Cash': {'symbol': 'BCH', 'color': '#b7fbe6'},
                        'Convex Finance': {'symbol': 'CVX', 'color': '#220881'},
                        'Shentu': {'symbol': 'CTK', 'color': '#ba7131'},
                        'BakeryToken': {'symbol': 'BAKE', 'color': '#3ec613'},
                        'Dego Finance': {'symbol': 'DEGO', 'color': '#c2fe6d'},
                        'EOS': {'symbol': 'EOS', 'color': '#27da49'}, 'Cosmos': {'symbol': 'ATOM', 'color': '#e783d1'},
                        'NEM': {'symbol': 'XEM', 'color': '#a568d0'}, 'DODO': {'symbol': 'DODO', 'color': '#1babc3'},
                        'DFI.Money': {'symbol': 'YFII', 'color': '#15484b'},
                        'Radicle': {'symbol': 'RAD', 'color': '#b8c995'},
                        'Travala.com': {'symbol': 'AVA', 'color': '#b77283'},
                        'Bitcoin': {'symbol': 'BTC', 'color': '#702abf'},
                        'Mdex': {'symbol': 'MDX', 'color': '#9c78b1'},
                        'Injective': {'symbol': 'INJ', 'color': '#999112'},
                        'iExec RLC': {'symbol': 'RLC', 'color': '#292a5f'},
                        'FTX Token': {'symbol': 'FTT', 'color': '#f8fa36'},
                        'Perpetual Protocol': {'symbol': 'PERP', 'color': '#370af6'},
                        'Serum': {'symbol': 'SRM', 'color': '#e68867'},
                        'Fantom': {'symbol': 'FTM', 'color': '#afe87e'},
                        'Voyager Token': {'symbol': 'VGX', 'color': '#3335dc'},
                        'Civic': {'symbol': 'CVC', 'color': '#bf6e59'},
                        'SuperRare': {'symbol': 'RARE', 'color': '#959af2'},
                        'FUNToken': {'symbol': 'FUN', 'color': '#41fa05'},
                        'Streamr': {'symbol': 'DATA', 'color': '#d76587'},
                        'Binance USD': {'symbol': 'BUSD', 'color': '#efe0c6'},
                        'Qtum': {'symbol': 'QTUM', 'color': '#de1d4f'},
                        'Neo': {'symbol': 'NEO', 'color': '#587df1'},
                        'Ontology Gas': {'symbol': 'ONG', 'color': '#a43d00'},
                        'Internet Computer': {'symbol': 'ICP', 'color': '#3556c3'},
                        'Hifi Finance': {'symbol': 'MFT', 'color': '#79880e'},
                        'Anchor Protocol': {'symbol': 'ANC', 'color': '#52364b'},
                        'Celer Network': {'symbol': 'CELR', 'color': '#a4aed7'},
                        'Axie Infinity': {'symbol': 'AXS', 'color': '#66afb6'},
                        'Aion': {'symbol': 'AION', 'color': '#6bce95'},
                        'Lido DAO': {'symbol': 'LDO', 'color': '#685f01'},
                        'Pax Dollar': {'symbol': 'USDP', 'color': '#2ec07f'},
                        'NKN': {'symbol': 'NKN', 'color': '#8f847f'}, 'Fetch.ai': {'symbol': 'FET', 'color': '#de4aa6'},
                        'Gala': {'symbol': 'GALA', 'color': '#633fff'}, 'Utrust': {'symbol': 'UTK', 'color': '#3317d8'},
                        'Terra': {'symbol': 'LUNA', 'color': '#e520ce'}, 'ICON': {'symbol': 'ICX', 'color': '#707b8b'},
                        'Smooth Love Potion': {'symbol': 'SLP', 'color': '#546b37'},
                        'Yield Guild Games': {'symbol': 'YGG', 'color': '#1c9f30'},
                        'Stratis': {'symbol': 'STRAX', 'color': '#c44771'},
                        'The Graph': {'symbol': 'GRT', 'color': '#1bd543'},
                        'Tezos': {'symbol': 'XTZ', 'color': '#5f0e9c'},
                        'VeThor Token': {'symbol': 'VTHO', 'color': '#3f357'},
                        'district0x': {'symbol': 'DNT', 'color': '#176c04'},
                        'BarnBridge': {'symbol': 'BOND', 'color': '#351aea'},
                        'Tellor': {'symbol': 'TRB', 'color': '#91ebd'},
                        'Sun (New)': {'symbol': 'SUN', 'color': '#df45eb'},
                        'Algorand': {'symbol': 'ALGO', 'color': '#cd3ad0'},
                        'Stacks': {'symbol': 'STX', 'color': '#9d68a9'},
                        'yearn.finance': {'symbol': 'YFI', 'color': '#a11f32'},
                        'Conflux': {'symbol': 'CFX', 'color': '#5b3246'},
                        'Solana': {'symbol': 'SOL', 'color': '#9abf09'},
                        'NEAR Protocol': {'symbol': 'NEAR', 'color': '#d615c3'},
                        'Hive': {'symbol': 'HIVE', 'color': '#be7e79'}}